Repository opentypejs/opentype.js, pull requests merged in 2023-02, with the labels that each got.

#549 make jshint and jscs ignore the /.git folder
  .jscsrc
  .jshintignore
Labels: dev

#562 make cffEncoding.charset fall back to CIDs instead of undefined
  src/tables/cff.js
  test/tables/cff.js
Labels: bug, Spec

#461 Set correctly unicode 0 to ".null" glyph
  README.md
  src/glyph.js
  test/opentypeSpec.js
Labels: Spec

#572 optimize performance by replacing modulus with bitwise operator
  src/hintingtt.js
  src/tables/cff.js
Labels: performance

#486 GSUB lookup table type 7 subtable format 1
  src/features/featureQuery.js
  test/tables/gsub.js
Labels: Spec

#576 Parsing and writing support for variable font tables fvar, STAT and avar
  src/opentype.js
  src/parse.js
  src/substitution.js
  src/tables/avar.js
  src/tables/fvar.js
  src/tables/gvar.js
  src/tables/sfnt.js
  src/tables/stat.js
  src/types.js
  src/util.js
  test/tables/avar.js
  test/tables/fvar.js
  test/tables/stat.js
  test/types.js
Labels: enhancement, Spec, writing support
